### ISSUE TITLE
Error at registration

### ISSUE THREAD

**Issue by kukko** [benhawley7/fortnite-api-io#1]
I tried to register through the dashboard, but I got the following error.

```
An error occured!

	SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xC5\x91' for column `fortniteapi`.`api_keys`.`owner` at row 1 


```
I hope you can fix it soon, because I want to try out your API.

Thanks for the great work, keep coding! :)

**Comment by kukko** [comment]
Excuse me, I just saw you are not the maintainer of https://fortniteapi.io/, so I close this issue.

**Comment by benhawley7** [comment]
> Excuse me, I just saw you are not the maintainer of https://fortniteapi.io/, so I close this issue.

No worries! :)
