### ISSUE TITLE
WindowID in Tournement Session Details

### ISSUE THREAD

**Issue by ImmortalDoesDev** [benhawley7/fortnite-api-io#10]
Where can I find the WindowID for tournament session details?

**Comment by benhawley7** [comment]
Hi @ImmortalEvil !

As I'm not the creator of the API, the best place to ask this question would be on the API's Discord  - there is a link on the homepage: https://fortniteapi.io/

But from what I can see - using the List Tournaments endpoint will return tournaments with their Window IDs! You can use the this repos Fortnite API client to do this like so: `const result = await client.getTournaments();`.

Hope this helps!
