### ISSUE TITLE
Issue with the wiki

### ISSUE THREAD

**Issue by PlainDevelopment** [benhawley7/fortnite-api-io#2]
At the top you defined the api as "fortniteAPI", but in the rest of the wiki it's referred to as "forniteAPI".

**Comment by benhawley7** [comment]
Thanks for pointing this out!

The wiki has been updated:
https://github.com/benhawley7/fortnite-api-io/wiki

This also revealed a spelling mistake in the FortniteAPI class in the code - not a major issue, will fix sometime soon.
